---
deployment:
  tasks:
    - export DEPLOYPATH=/home4/cahworks/public_html/
    - /bin/cp build/index.html $DEPLOYPATH
    - /bin/cp -R /build/static/css $DEPLOYPATH
    - /bin/cp -R /build/static/js $DEPLOYPATH
    - /bin/cp -R /build/static/media $DEPLOYPATH
