---
deployment:
  tasks:
    - export DEPLOYPATH=/home4/cahworks/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R static/css $DEPLOYPATH
    - /bin/cp -R static/js $DEPLOYPATH
    - /bin/cp -R static/media $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R src $DEPLOYPATH